### ISSUE TITLE
Previous courses - missing material and information

### ISSUE THREAD

**Issue by arnima-github** [admb-project/admb-project.github.io#3]
The webpage

  http://www.admb-project.org/courses/

presents a list of previous ADMB/TMB courses, but the list is missing some course material (files) and information.

For example, clicking on March 2009 results in a 404 error. The same is true for July 2009, August 2009, and July 2010.

An older page, http://admb-project-org.admb-foundation.org/events/previous/march-2009, provides links to material (files). The older page also provides additional information, for example, that the workshop took place in Santa Barbara.

Hopefully, the previous courses can be successfully transferred to the new website. The older page, http://admb-project-org.admb-foundation.org/events/previous, lists all the venues upfront, which is helpful.

**Comment by dobieszn** [comment]
The link on the courses page (near the bottom of the page) to Training Videos by Quantitative Fisheries Center, Michigan State University seems to be broken.  Not sure what happened.  The link should point to our FTP site ftp://glpd.fw.msu.edu/QFC/ADMB-Videos where we keep the videos.
