### ISSUE TITLE
Current list of publications citing ADMB

### ISSUE THREAD

**Issue by arni-magnusson** [admb-project/admb-project.github.io#6]
The webpage

http://www.admb-project.org/community/bibliography/

lists around 170 publications using ADMB. However, it is hard work to update this list and it contains no papers published after 2013...

A better solution would probably to provide a link to Google Scholar, which keeps track of all publications citing ADMB,

https://scholar.google.com/scholar?cites=16400103810565540667

or the same list sorted by date:

https://scholar.google.com/scholar?cites=16400103810565540667&scisbd=1

**Comment by colemonnahan** [comment]
Trevor and I did a lit review for citations of ADMB and TMB for a recent paper. Would it help to dig that up? Here's an early draft of what it looks like. Trevor did all the work.

[Draft.pdf](https://github.com/admb-project/admb-project.github.io/files/462012/Draft.pdf)

**Comment by johnrsibert** [comment]
I sort of like Arni's suggestion of using google scholar, but the list is not very succinct.
